# Generated by Django 2.2 on 2019-06-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190607_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='items',
            name='tag',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
