# Generated by Django 2.2 on 2019-06-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190623_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
