# Generated by Django 2.2 on 2019-06-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_items_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='discount_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
